<?xml version="1.0" encoding="utf-8"?><Database Name="verk2013_hopur09" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=hrnem.ru.is;Initial Catalog=verk2013_hopur09;Persist Security Info=True;User ID=hopur09_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="verk2013_hopur09ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dateofSignup" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="userRating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_UserRating" Member="UserRatings" ThisKey="Id" OtherKey="idRater" Type="UserRating" />
      <Association Name="User_UserRating1" Member="UserRatings1" ThisKey="Id" OtherKey="idUser" Type="UserRating" />
      <Association Name="User_GroupMember" Member="GroupMembers" ThisKey="Id" OtherKey="idUser" Type="GroupMember" />
    </Type>
  </Table>
  <Table Name="dbo.UserRatings" Member="UserRatings">
    <Type Name="UserRating">
      <Column Name="idRater" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="positive" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="review" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="User_UserRating" Member="User" ThisKey="idRater" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_UserRating1" Member="User1" ThisKey="idUser" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Group">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="owner" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Group_GroupMember" Member="GroupMembers" ThisKey="Id" OtherKey="idGroup" Type="GroupMember" />
    </Type>
  </Table>
  <Table Name="dbo.GroupMembers" Member="GroupMembers">
    <Type Name="GroupMember">
      <Column Name="idGroup" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Group_GroupMember" Member="Group" ThisKey="idGroup" OtherKey="Id" Type="Group" IsForeignKey="true" />
      <Association Name="User_GroupMember" Member="User" ThisKey="idUser" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>